version: '3'

services:
  node:
    build: .
    image: node
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/videoclub
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
    networks:
      - node-network
    command: yarn start

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
